language: node_js
node_js:
- '0.10'
before_script:
- npm install -g protractor
- webdriver-manager update
- node_modules/.bin/jspm install
script: protractor e2e/conf.js
 # - node_modules/karma/bin/karma start karma.conf.js --single-run
 # - node_modules/protractor/bin/protractor e2e/conf.js
deploy:
  provider: divshot
  environment:
    production: production
  skip_cleanup: true
  api_key:
    secure: NLflGinOFxOWn3BRFXEofy0WkA+kPTdRKVZerApgkIuN54hyFZV17xqmyf03yIhfKEOSKfla+N4FiubRGkKOjVJSKfAu2eOZI9SYSjFtXldaoUUeS99iR5XKu2ec9uwdc8BIlRkdWU08NWeN94lKXcVS/0NByVnKy3GGV/lb2co=
  on:
    tags: true
    all_branches: true