language: node_js
node_js:
- '0.10'
before_script:
- node_modules/.bin/jspm install
script:
- node_modules/karma/bin/karma start karma.conf.js --single-run
- divshot push development -t $DIVSHOT_KEY
- node_modules/protractor/bin/protractor --baseUrl='http://development.fatburnhub.com' e2e/conf.js
- divshot push staging -t $DIVSHOT_KEY
- node_modules/protractor/bin/protractor --baseUrl='http://staging.fatburnhub.com' e2e/conf.js
- divshot promote staging production
# deploy:
#   provider: divshot
#   environment:
#     production: production
#   skip_cleanup: true
#   api_key:
#     secure: NLflGinOFxOWn3BRFXEofy0WkA+kPTdRKVZerApgkIuN54hyFZV17xqmyf03yIhfKEOSKfla+N4FiubRGkKOjVJSKfAu2eOZI9SYSjFtXldaoUUeS99iR5XKu2ec9uwdc8BIlRkdWU08NWeN94lKXcVS/0NByVnKy3GGV/lb2co=
#   on:
#     tags: true
#     all_branches: true